### ISSUE TITLE
Subtle bug in cal_futureonly.pl

### ISSUE THREAD

**Issue by mlmatlock** [jbalcorn/ical2rem#7]
Here's a head banger:

futureonly.pl does a great job in cutting excess entries, but...

If an event is entered in Google Calendar, and you set it as a repeating event, futureonly adds an additional event for the following day (for the original *and* repeating events)

Ex:  Add an event in google cal for 8 Oct (all day), and set it to repeat every 2 weeks.  

Downloading the .ics and running only ical2rem produces the desired output for remind (8 and 22 Oct, 5 and 19 Nov, etc).

If you run futureonly on the .ics file *before* ical2rem, you end up with 8, 9, 22 and 23 Oct, and 5, 6, 19 and 20 Nov (and continuing).

**Comment by jbalcorn** [comment]
Is this only on all day events, or does it happen on shorter events?

**Comment by mlmatlock** [comment]
When I made a timed (15-1600), repeating every 2 weeks, it came out fine.  Upside, is that it cleared the original problem, and I couldn't get it to duplicate.

Must've been *something* funky in the original .ics file that isn't here anymore.

Thanks for your help!
